### PR TITLE
upgrade to ruby 2.4.3 and fix logic: Hash has to_proc method in ruby …

### PR DESCRIPTION
**Pull request by sonncui**
upgrade to ruby 2.4.3 and fix logic: Hash has to_proc method in ruby 2.4.3

### CODE REVIEW

**Comment by mdub** [comment]
I can see the problem, here. 

I really don't like having a special-case for `Hash`, though. I'd like to investigate other ways of fixing this, first.

**Comment by sonncui** [comment]
ok, I'll track it too. Thanks a lot.

**Comment by sonncui** [comment]
@mdub We have change the implementation of fix the issue caused by upgrade ruby to 2.4.3.
Would you help to review it?
We expect your feedback, thanks a lot!

**Comment by mdub** [comment]
Thanks @sonncui. I quite like your approach of testing `kind_of?(Proc)`, rather than `respond_to?(:to_proc)` - especially as it avoids a special-case for Hash.

The test wasn't in quite the right place, so I've fixed it up, and committed in 4eaa5f8. You happy with that?

**Comment by sonncui** [comment]
Of course, awesome! Thanks a lot!
We're working on a REA project and rely on the new changes of representative. 
Would you help to release the new changes for us to use it? Thanks a lot!

**Comment by mdub** [comment]
Closed in favour of 4eaa5f8.

Fix released as `v1.2.0`.

**Pull request closed without merging**
